matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
      osx_iamge: xcode8

language: generic

install:
  - npm install -g grunt-cli
  - npm install
  - pip install requests
  - make -C server deps
script:
  - grunt
  - make -C server all test

after_success:
  - '[ -n "$TRAVIS_TAG" ] && server/upload_github_release.py'
